### ISSUE TITLE
umeng统计到的2个crash

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogV3#107]
implementation 'com.kongzue.dialog_v3x:dialog:3.1.6'
###################第一个######################
Caused by: java.lang.NullPointerException: Attempt to invoke direct method 'void com.kongzue.dialog.v3.TipDialog.autoDismiss()' on a null object reference
    at com.kongzue.dialog.v3.TipDialog.show(TipDialog.java:167)
    at com.agz.clock.activity.shed.BindShedActivity.showSuccessTipDialog(BindShedActivity.kt:259)
    at com.agz.clock.activity.shed.BindShedActivity.access$showSuccessTipDialog(BindShedActivity.kt:63)
    at com.agz.clock.activity.shed.BindShedActivity$socketListener$1$onBardLocationSuccess$1.accept(BindShedActivity.kt:349)
    at com.agz.clock.activity.shed.BindShedActivity$socketListener$1$onBardLocationSuccess$1.accept(BindShedActivity.kt:314)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    ... 10 more
java.lang.NullPointerException: Attempt to invoke direct method 'void com.kongzue.dialog.v3.TipDialog.autoDismiss()' on a null object reference
    at com.kongzue.dialog.v3.TipDialog.show(TipDialog.java:167)
    at com.agz.clock.activity.shed.BindShedActivity.showSuccessTipDialog(BindShedActivity.kt:259)
    at com.agz.clock.activity.shed.BindShedActivity.access$showSuccessTipDialog(BindShedActivity.kt:63)
    at com.agz.clock.activity.shed.BindShedActivity$socketListener$1$onBardLocationSuccess$1.accept(BindShedActivity.kt:349)
    at com.agz.clock.activity.shed.BindShedActivity$socketListener$1$onBardLocationSuccess$1.accept(BindShedActivity.kt:314)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

#########################第二个#############################
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
    at com.kongzue.dialog.util.BaseDialog.doDismiss(BaseDialog.java:240)
    at com.kongzue.dialog.v3.TipDialog.dismiss(TipDialog.java:422)
    at com.kongzue.dialog.v3.TipDialog$5.run(TipDialog.java:249)
    at java.util.TimerThread.mainLoop(Timer.java:562)
    at java.util.TimerThread.run(Timer.java:512)

**Comment by kongzue** [comment]
您好，如果您正在使用support版本请更新至 3.1.6.6 测试版本，AndroidX请等待后续正式版本更新。

**Comment by kongzue** [comment]
长时间未收到您的回复，暂时关闭此问题，如有需要可以继续回复
