### ISSUE TITLE
点通知  什么都没有弹出

### ISSUE THREAD

**Issue by leejunkiboy** [kongzue/DialogV3#114]
点通知  什么都没有弹出
以前Dialog是好的, 现在转这个V3 DialogFragment版 点通知弹不出来

**Comment by leejunkiboy** [comment]
2019-12-23 12:33:45.084 4920-4920/com.kongzue.dialogdemo W/TypefaceUtils: get metaData of com.kongzue.dialogdemo failed
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
        at miui.util.TypefaceUtils.isUsingMiuiFont(TypefaceUtils.java:300)
        at miui.util.TypefaceUtils.usingMiuiFonts(TypefaceUtils.java:289)
        at miui.util.TypefaceUtils.replaceTypeface(TypefaceUtils.java:570)
        at android.widget.TextView.replaceTypeface(TextView.java:4380)
        at android.widget.TextView.setTypeface(TextView.java:4369)
        at android.widget.TextView.setTypeface(TextView.java:2251)
        at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2157)
        at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2128)
        at android.widget.TextView.applyTextAppearance(TextView.java:4083)
        at android.widget.TextView.<init>(TextView.java:1604)
        at android.widget.TextView.<init>(TextView.java:968)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.kongzue.dialog.v3.Notification.showIOSNotification(Notification.java:351)
        at com.kongzue.dialog.v3.Notification.showNotification(Notification.java:253)
        at com.kongzue.dialog.v3.Notification.show(Notification.java:197)
        at com.kongzue.dialogdemo.MainActivity$8.onClick(MainActivity.java:386)
        at android.view.View.performClick(View.java:7160)
        at android.view.View.performClickInternal(View.java:7137)
        at android.view.View.access$3500(View.java:810)
        at android.view.View$PerformClick.run(View.java:27418)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by leejunkiboy** [comment]
真正的问题在这里
No field mParams in class Landroid/widget/Toast$TN; (declaration of 'android.widget.Toast$TN' appears in /system/framework/framework.jar!classes3.dex)

kToast  下面的  show()方法
里面有个反射
Field tnParamsField = mTN.getClass().getDeclaredField("mParams");

这里是没有mParams

**Comment by kongzue** [comment]
请参考常见问题：
![Snipaste_2019-12-23_19-48-59](https://user-images.githubusercontent.com/10115359/71356470-4a129580-25bd-11ea-95e2-380ff853ed1c.png)

**Comment by xiaomeixw** [comment]
小米真坑~~
