### ISSUE TITLE
在后台会偶然出现这个问题导致APP崩溃

### ISSUE THREAD

**Issue by XinHaoLeo** [kongzue/DialogV3#123]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kongzue.dialog.util.DialogHelper.dismiss()' on a null object reference
        at com.kongzue.dialog.util.BaseDialog.doDismiss(BaseDialog.java:241)
        at com.kongzue.dialog.v3.TipDialog$5.run(TipDialog.java:253)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by kongzue** [comment]
如果您正在使用support版本，请更新至3.1.7.4测试版本，或等待正式版本修复，如果你正在使用AndroidX版本，请等待正式版修复。

**Comment by XinHaoLeo** [comment]
好,谢谢
