### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by UserNameQC** [kongzue/DialogV3#153]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kongzue.dialog.util.view.ProgressView.setup(int)' on a null object reference
        at com.kongzue.dialog.v3.TipDialog.refreshView(TipDialog.java:304)
        at com.kongzue.dialog.v3.TipDialog.bindView(TipDialog.java:244)
        at com.kongzue.dialog.util.DialogHelper.findMyParentAndBindView(DialogHelper.java:227)
        at com.kongzue.dialog.util.DialogHelper.onCreateView(DialogHelper.java:70)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

应用打开就 出现这个问题  ，如何解决

**Comment by kongzue** [comment]
请更新至3.1.9.3版本尝试是否解决此问题，或等待后续正式版本更新

**Comment by UserNameQC** [comment]
ok

**Comment by kongzue** [comment]
暂时关闭此问题，有任何需要可以继续留言
