### ISSUE TITLE
3.2.1版本的CustomDialog在设置setAlign(BaseDialog.ALIGN.BOTTOM)后无法铺满宽度了吗？

### ISSUE THREAD

**Issue by ppg408331701** [kongzue/DialogV3#169]
之前在3.1.9是可以铺满宽度的。现在会有大概20dp的margin。

是否有什么方法可以指定是否铺满宽度？

```
  CustomDialog.build(mActivity, R.layout.dialog_nim_subcribe_duration) { dialog, v ->
            v.findViewById<View>(R.id.tv_cancle).setOnClickListener { dialog.doDismiss() }
        }
            .setAlign(CustomDialog.ALIGN.BOTTOM)
            .show()
```

**Comment by ppg408331701** [comment]
![538e0d39266505824c89bc4c00259c8](https://user-images.githubusercontent.com/16531268/87408976-dedeee00-c5f6-11ea-8c1a-8c1620f4202d.jpg)

**Comment by ppg408331701** [comment]
![566c861032379619a8f0d991b91915f](https://user-images.githubusercontent.com/16531268/87409372-6c224280-c5f7-11ea-8cfd-058c6f8ec9bc.jpg)

这是同样的代码在3.1.9下的表现。

**Comment by kongzue** [comment]
此问题已经在最新的测试版中解决，等待上正式版中。
如果您正在使用Support版本，可以尝试升级至3.2.1.1测试版本，使用如下方法：
```
customDialog.setCustomLayoutParams(new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT))
```
即可启用横向全屏的效果。

**Comment by wangcaiwen5** [comment]
Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
        at com.kongzue.dialog.util.DialogHelper.refreshDialogPosition(DialogHelper.java:148)
        at com.kongzue.dialog.util.DialogHelper.onCreateDialog(DialogHelper.java:95)
        at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328)
        at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)

**Comment by wangcaiwen5** [comment]
如果使用3.2.1.1  不设置setCustomLayoutParams会报错哦 建议兼容一下吧

Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
        at com.kongzue.dialog.util.DialogHelper.refreshDialogPosition(DialogHelper.java:148)
        at com.kongzue.dialog.util.DialogHelper.onCreateDialog(DialogHelper.java:95)
        at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328)
        at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)

**Comment by kongzue** [comment]
最新的测试版本已经修复，请等待正式版更新，或更新至3.2.1.4测试版本
