### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by oudengding** [kongzue/DialogV3#185]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yuanli.mvpuscs, PID: 32078
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOnKeyListener(android.content.DialogInterface$OnKeyListener)' on a null object reference
        at com.kongzue.dialog.util.BaseDialog$2.onShow(BaseDialog.java:218)
        at com.kongzue.dialog.util.DialogHelper$2.onShow(DialogHelper.java:132)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8293)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by Mc-dashan** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setOnKeyListener(android.content.DialogInterface$OnKeyListener)' on a null object reference
        at com.kongzue.dialog.util.BaseDialog$2.onShow(BaseDialog.java:218)
        at com.kongzue.dialog.util.DialogHelper$2.onShow(DialogHelper.java:132)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1581)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


俺也一样  最新版本

**Comment by kongzue** [comment]
@Mc-dashan 很抱歉这应该是一个失误造成的，请更新至测试版本（Support） 3.2.3.2 修复此问题。

**Comment by Mc-dashan** [comment]
谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kongzue/DialogV3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 中午11:52
收件人:&nbsp;"kongzue/DialogV3"<DialogV3@noreply.github.com&gt;;
抄送:&nbsp;"史贺"<936112399@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kongzue/DialogV3] 空指针异常 (#185)





 
@Mc-dashan 很抱歉这应该是一个失误造成的，请更新至测试版本（Support） 3.2.3.2 修复此问题。

**Comment by oudengding** [comment]
OK

**Comment by Txxyyy** [comment]
我也是
java.lang.NullPointerException

Attempt to invoke virtual method 'void android.app.Dialog.setOnKeyListener(android.content.DialogInterface$OnKeyListener)' on a null object reference

请问如何解决？切换不了2.3.2.2版本

**Comment by kongzue** [comment]
@Txxyyy 正式版都更新到3.2.3了，不再讨论老版本的问题。

**Comment by kongzue** [comment]
@Txxyyy 已经更新最新的正式版本 3.2.4，请尝试使用此版本，问题已经修复
