### ISSUE TITLE
您好，帮忙看一下这个出错的问题

### ISSUE THREAD

**Issue by Mc-dashan** [kongzue/DialogV3#189]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isDestroyed()' on a null object reference
        at com.kongzue.dialog.util.BaseDialog.showNext(BaseDialog.java:165)
        at com.kongzue.dialog.util.BaseDialog$1.onDismiss(BaseDialog.java:142)
        at com.kongzue.dialog.util.DialogHelper.onDismiss(DialogHelper.java:330)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1323)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by kongzue** [comment]
请勿使用空指针引用的context启动Dialog
