### ISSUE TITLE
能帮忙看一下这个问题吗？

### ISSUE THREAD

**Issue by KasuganoSora2020** [kongzue/DialogV3#198]
2020-09-18 17:52:44.668 7937-7937
: ******** app crash : java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:433)
        at android.view.View.<init>(View.java:4595)
        at android.view.View.<init>(View.java:4741)
        at android.view.View.<init>(View.java:4704)
        at android.view.View.<init>(View.java:4683)
        at com.kongzue.dialog.util.view.BlurView.<init>(BlurView.java:57)
        at com.kongzue.dialog.v3.MessageDialog$1.run(MessageDialog.java:283)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

某些Activity调用没问题，某些Activity会崩溃

**Comment by kongzue** [comment]
很可能是传入的context指向了一个空指针，请确保启动Dialog时使用的Context不为空

**Comment by kongzue** [comment]
您好，长时间未收到回复暂时关闭此问题，如有疑问可以继续回复。
