### ISSUE TITLE
v3.2.4 显示底部菜单崩溃

### ISSUE THREAD

**Issue by HubertYoung** [kongzue/DialogV3#201]
2020-09-23 15:17:31.964 30147-30147/com.kongzue.dialogdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kongzue.dialogdemo, PID: 30147
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
        at java.util.ArrayList.<init>(ArrayList.java:191)
        at com.kongzue.dialog.v3.BottomMenu.setMenuTextList(BottomMenu.java:666)
        at com.kongzue.dialogdemo.MainActivity$9.onClick(MainActivity.java:447)
        at android.view.View.performClick(View.java:7252)
        at android.view.View.performClickInternal(View.java:7229)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27765)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-09-23 15:17:31.966 2815-2815/? E/Indicator: not support setTranslationX

解决如下
![image](https://user-images.githubusercontent.com/20985039/93980353-17e2ce00-fdb1-11ea-9e3e-e9742fea0b5a.png)

**Comment by kongzue** [comment]
是不是给进去个null啊...

**Comment by HubertYoung** [comment]
入参就没使用哦

**Comment by Adolphsa** [comment]
List<CharSequence> aa = new ArrayList<>();
aa.add("我要删除");
采用这种方式可以创建成功。
直接new String（）｛｝会崩溃。
