### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by qq380791741** [kongzue/DialogV3#241]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.appcompat.app.AppCompatActivity.isDestroyed()' on a null object reference
	at com.kongzue.dialog.util.BaseDialog.showNext(BaseDialog.java:165)
	at com.kongzue.dialog.util.BaseDialog$1.onDismiss(BaseDialog.java:142)
	at com.kongzue.dialog.util.DialogHelper.onDismiss(DialogHelper.java:330)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1414)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7829)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:986)
Back traces ends.

在调用isDestroyed方法的时候是否应该判断下 activity是否为null呢

**Comment by qq380791741** [comment]
用的com.kongzue.dialog_v3x:dialog:3.2.4
