### ISSUE TITLE
Android 4.4下使用ShareDialog出现闪退

### ISSUE THREAD

**Issue by idol2001** [kongzue/DialogV3#40]
目前发现此问题都是在Android 4.4版本机器上，包括OPPO R7, 联想小S，联想 S90
表现是调用ShareDialog.show方法就会报错
具体异常信息如下：
android.view.InflateException: Binary XML file line #2: Error inflating class &lt;unknown&gt;
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.kongzue.dialog.v3.ShareDialog.refreshView(ShareDialog.java:278)
	at com.kongzue.dialog.v3.ShareDialog.bindView(ShareDialog.java:121)
	at com.kongzue.dialog.util.DialogHelper.findMyParentAndBindView(DialogHelper.java:165)
	at com.kongzue.dialog.util.DialogHelper.onCreateView(DialogHelper.java:69)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:222)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 29 more
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101045c a=-1}
	at android.content.res.Resources.loadDrawable(Resources.java:2266)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.&lt;init&gt;(View.java:3598)
	at android.view.ViewGroup.&lt;init&gt;(ViewGroup.java:500)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:188)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:183)
	... 32 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.kongzue.dialog.v3.ShareDialog.refreshView(ShareDialog.java:278)
	at com.kongzue.dialog.v3.ShareDialog.bindView(ShareDialog.java:121)
	at com.kongzue.dialog.util.DialogHelper.findMyParentAndBindView(DialogHelper.java:165)
	at com.kongzue.dialog.util.DialogHelper.onCreateView(DialogHelper.java:69)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:222)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101045c a=-1}
	at android.content.res.Resources.loadDrawable(Resources.java:2266)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.&lt;init&gt;(View.java:3598)
	at android.view.ViewGroup.&lt;init&gt;(ViewGroup.java:500)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:188)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:183)
	... 32 more
android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101045c a=-1}
	at android.content.res.Resources.loadDrawable(Resources.java:2266)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.&lt;init&gt;(View.java:3598)
	at android.view.ViewGroup.&lt;init&gt;(ViewGroup.java:500)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:188)
	at android.widget.LinearLayout.&lt;init&gt;(LinearLayout.java:183)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.kongzue.dialog.v3.ShareDialog.refreshView(ShareDialog.java:278)
	at com.kongzue.dialog.v3.ShareDialog.bindView(ShareDialog.java:121)
	at com.kongzue.dialog.util.DialogHelper.findMyParentAndBindView(DialogHelper.java:165)
	at com.kongzue.dialog.util.DialogHelper.onCreateView(DialogHelper.java:69)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:222)
	at android.app.ActivityThread.main(ActivityThread.java:5484)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by kongzue** [comment]
请更新至 3.1.0.4 内测版本，或后续正式版本，已经解决此问题。
此问题导致原因是因为是用了 API-21 才支持的 Material 水波纹效果但忽略了低版本 API 可能存在的兼容问题，现已得到修复。

**Comment by idol2001** [comment]
非常感谢您的及时回复！3.1.0.4内测版本是不是还没有提交？我更新到了3.1.0.2但是还没有解决这个问题。我可以等待您提交3.1.0.4内测版本或正式版本，再次感谢！

**Comment by kongzue** [comment]
具体解决办法与代码变动我有发简书：https://www.jianshu.com/p/27cbf0f57c46
测试版本因为可能还牵扯代码变动一般不会提交，在正式版发布后会连同所有更新一次性提交上来。
